; Exemplo cobrindo tokens adicionados em scheme.flex/scheme.y.
(define hex #x10)
(define bin #b11)
(define metade 1/2)
(define letra #\A)
(define lista '(a b c))
(define par '(a . b))
(define vetor #(1 2 3))

(display (+ hex bin metade))
(newline)
(display letra)
(newline)
(display lista)
(newline)
(display par)
(newline)
(display vetor)
(newline)
